import type { BundeslandCode } from "./types";

export type CityData = {
  slug: string;
  name: string;
  bundesland: BundeslandCode;
  bundeslandName: string;
  einwohner: string;
  besonderheiten: string[];
  preishinweis: string;
  halteverbotKosten: string;
  /** km für Lokal-Beispiel */
  lokalKm: number;
  /** km für Langstrecken-Beispiel */
  fernKm: number;
  fernZiel: string;
};

export const CITIES: CityData[] = [
  {
    slug: "aachen",
    name: "Aachen",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 250.000",
    besonderheiten: [
      "Grenzstadt zu Belgien und den Niederlanden — viele internationale Umzüge",
      "RWTH Aachen sorgt für eine der höchsten Studierenden-Umzugsfrequenzen Deutschlands",
      "Historische Altstadt mit engen Gassen und Zugangsbeschränkungen",
      "Moderate Mietpreise im NRW-Vergleich",
    ],
    preishinweis:
      "Aachen liegt preislich im unteren NRW-Mittelfeld. Die starke Studierenden-Nachfrage sorgt für guten Wettbewerb unter Umzugsfirmen.",
    halteverbotKosten: "80–180 €",
    lokalKm: 12,
    fernKm: 590,
    fernZiel: "Berlin",
  },
  {
    slug: "augsburg",
    name: "Augsburg",
    bundesland: "BY",
    bundeslandName: "Bayern",
    einwohner: "ca. 300.000",
    besonderheiten: [
      "Universitätsstadt mit vielen Studierenden-Umzügen",
      "Günstigere Alternative zu München bei bayerischem Regionalfaktor",
      "Viele Altbauwohnungen in der Innenstadt",
      "Gute Autobahnanbindung über die A8",
    ],
    preishinweis:
      "Augsburg ist deutlich günstiger als München, profitiert aber von der guten Infrastruktur und Anbindung im bayerischen Raum.",
    halteverbotKosten: "100–200 €",
    lokalKm: 15,
    fernKm: 550,
    fernZiel: "Hamburg",
  },
  {
    slug: "berlin",
    name: "Berlin",
    bundesland: "BE",
    bundeslandName: "Berlin",
    einwohner: "3,7 Mio.",
    besonderheiten: [
      "Hoher Altbau-Anteil mit engen Treppenhäusern",
      "Halteverbotszonen oft Pflicht in Innenstadtbezirken",
      "Hinterhöfe und Seitenflügel erschweren den Zugang",
      "Parkplatzsituation in Friedrichshain, Kreuzberg, Neukölln besonders angespannt",
    ],
    preishinweis:
      "Berlin liegt preislich im oberen Mittelfeld. Altbau-Zuschläge und lange Laufwege treiben die Kosten häufig über den reinen Volumen-Richtwert.",
    halteverbotKosten: "ab ca. 68 €",
    lokalKm: 25,
    fernKm: 600,
    fernZiel: "München",
  },
  {
    slug: "bielefeld",
    name: "Bielefeld",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 340.000",
    besonderheiten: [
      "Kompakte Stadtstruktur mit kurzen Wegen",
      "Nähe zum Teutoburger Wald",
      "Moderate Mietpreise im NRW-Vergleich",
      "Gute Erreichbarkeit über die A2",
    ],
    preishinweis:
      "Bielefeld bietet moderate Umzugspreise im NRW-Vergleich, die kompakte Stadtstruktur hält die Lokalumzugskosten niedrig.",
    halteverbotKosten: "80–180 €",
    lokalKm: 12,
    fernKm: 450,
    fernZiel: "München",
  },
  {
    slug: "bochum",
    name: "Bochum",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 365.000",
    besonderheiten: [
      "Ruhrgebiet-Zentrum mit dichtem Netz an Umzugsfirmen",
      "Viele Zechengeländer wurden zu Wohnquartieren umgewandelt",
      "Ruhr-Universität sorgt für regelmäßige Studierenden-Umzüge",
      "Kurze Wege zu Dortmund, Essen und Gelsenkirchen",
    ],
    preishinweis:
      "Bochum bietet typische Ruhrgebiet-Preise im moderaten Bereich, leicht unter dem Bundesdurchschnitt.",
    halteverbotKosten: "80–170 €",
    lokalKm: 12,
    fernKm: 520,
    fernZiel: "Berlin",
  },
  {
    slug: "bonn",
    name: "Bonn",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 335.000",
    besonderheiten: [
      "Ehemalige Bundeshauptstadt mit vielen Bundesbehörden",
      "Rhein-Nähe beeinflusst Routenplanung",
      "Parkplatzsituation in der Südstadt besonders schwierig",
      "Hoher Anteil an berufsbedingten Umzügen",
    ],
    preishinweis:
      "Bonn liegt durch die Bundesbehörden-Nachfrage leicht über dem NRW-Durchschnitt, besonders in der Südstadt und Bad Godesberg.",
    halteverbotKosten: "100–220 €",
    lokalKm: 15,
    fernKm: 580,
    fernZiel: "Berlin",
  },
  {
    slug: "braunschweig",
    name: "Braunschweig",
    bundesland: "NI",
    bundeslandName: "Niedersachsen",
    einwohner: "ca. 250.000",
    besonderheiten: [
      "TU Braunschweig sorgt für viele Studierenden-Umzüge",
      "VW-Nähe bringt berufsbedingte Umzüge",
      "Vergleichsweise günstige Mieten",
      "Viele Neubaugebiete am Stadtrand",
    ],
    preishinweis:
      "Braunschweig bietet günstige Umzugspreise im niedersächsischen Mittelfeld mit guter Verfügbarkeit lokaler Anbieter.",
    halteverbotKosten: "80–170 €",
    lokalKm: 12,
    fernKm: 500,
    fernZiel: "München",
  },
  {
    slug: "bremen",
    name: "Bremen",
    bundesland: "HB",
    bundeslandName: "Bremen",
    einwohner: "570.000",
    besonderheiten: [
      "Kompakte Stadtstruktur — kurze Wege",
      "Schnoorviertel und Altstadt: enge Gassen",
      "Gute Anbindung nach Hamburg und Hannover",
      "Moderate Preise im norddeutschen Vergleich",
    ],
    preishinweis:
      "Bremen liegt auf Bundesdurchschnitt. Die kurzen Stadtwege halten die Lokalumzugskosten oft im unteren Bereich.",
    halteverbotKosten: "ab ca. 60 €",
    lokalKm: 15,
    fernKm: 400,
    fernZiel: "München",
  },
  {
    slug: "chemnitz",
    name: "Chemnitz",
    bundesland: "SN",
    bundeslandName: "Sachsen",
    einwohner: "ca. 250.000",
    besonderheiten: [
      "Kulturhauptstadt Europas 2025",
      "Niedrigstes Mietniveau unter den deutschen Großstädten",
      "Leerstand erleichtert die Wohnungssuche erheblich",
      "Viele sanierte Altbauten zu günstigen Preisen",
    ],
    preishinweis:
      "Chemnitz gehört zu den günstigsten Großstädten Deutschlands — sowohl bei Mieten als auch bei Umzugskosten.",
    halteverbotKosten: "60–150 €",
    lokalKm: 10,
    fernKm: 500,
    fernZiel: "Düsseldorf",
  },
  {
    slug: "darmstadt",
    name: "Darmstadt",
    bundesland: "HE",
    bundeslandName: "Hessen",
    einwohner: "ca. 160.000",
    besonderheiten: [
      "Wissenschaftsstadt mit TU Darmstadt und ESA-Standort",
      "Hohe Nachfrage durch Pendler ins Rhein-Main-Gebiet",
      "Mietpreise deutlich über hessischem Durchschnitt",
      "Gut ausgebautes Straßenbahnnetz erleichtert lokale Logistik",
    ],
    preishinweis:
      "Darmstadt liegt preislich im oberen hessischen Bereich — die Nähe zu Frankfurt und der angespannte Wohnungsmarkt treiben die Kosten.",
    halteverbotKosten: "100–200 €",
    lokalKm: 12,
    fernKm: 560,
    fernZiel: "Berlin",
  },
  {
    slug: "dortmund",
    name: "Dortmund",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "590.000",
    besonderheiten: [
      "Vergleichsweise günstiges Preisniveau im Ruhrgebiet",
      "Gute Autobahnanbindung für Fernumzüge",
      "Viele Mehrfamilienhäuser ohne Aufzug",
      "Kurze Wege zu Nachbarstädten (Essen, Bochum)",
    ],
    preishinweis:
      "Das Ruhrgebiet bietet moderate Umzugspreise. Dortmund liegt leicht über dem Schnitt, aber deutlich unter München oder Hamburg.",
    halteverbotKosten: "ab ca. 60 €",
    lokalKm: 15,
    fernKm: 500,
    fernZiel: "Berlin",
  },
  {
    slug: "dresden",
    name: "Dresden",
    bundesland: "SN",
    bundeslandName: "Sachsen",
    einwohner: "560.000",
    besonderheiten: [
      "Günstigstes Preisniveau unter den Großstädten",
      "Viele sanierte Gründerzeit-Altbauten in der Neustadt",
      "Elbhang-Lagen können Zufahrt erschweren",
      "Guter Umzugsmarkt mit vielen lokalen Anbietern",
    ],
    preishinweis:
      "Dresden profitiert vom sächsischen Preisvorteil (-5 %). Auch bei gehobener Ausstattung bleibt das Niveau moderat.",
    halteverbotKosten: "ab ca. 50 €",
    lokalKm: 15,
    fernKm: 450,
    fernZiel: "Frankfurt",
  },
  {
    slug: "duesseldorf",
    name: "Düsseldorf",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "620.000",
    besonderheiten: [
      "Medienhafen und Altstadt — unterschiedliche Zugangssituationen",
      "Gute Verfügbarkeit von Umzugsfirmen im Rheinland",
      "Rheinüberquerung bei stadtübergreifenden Umzügen",
      "Viele Pendler-Umzüge aus/nach Köln und dem Ruhrgebiet",
    ],
    preishinweis:
      "Düsseldorf liegt leicht über dem Bundesdurchschnitt. Die Nähe zu Köln und dem Ruhrgebiet sorgt für guten Preiswettbewerb.",
    halteverbotKosten: "ab ca. 65 €",
    lokalKm: 15,
    fernKm: 550,
    fernZiel: "München",
  },
  {
    slug: "duisburg",
    name: "Duisburg",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 500.000",
    besonderheiten: [
      "Europas größter Binnenhafen",
      "Deutliches Nord-Süd-Gefälle bei Mietpreisen",
      "Viele Altbauwohnungen in den südlichen Stadtteilen",
      "Gute Autobahnanbindung im Ruhrgebiet",
    ],
    preishinweis:
      "Duisburg bietet im Ruhrgebiet moderate Umzugspreise mit deutlichen Unterschieden je nach Stadtteil.",
    halteverbotKosten: "100–200 €",
    lokalKm: 15,
    fernKm: 570,
    fernZiel: "Berlin",
  },
  {
    slug: "erfurt",
    name: "Erfurt",
    bundesland: "TH",
    bundeslandName: "Thüringen",
    einwohner: "ca. 215.000",
    besonderheiten: [
      "Landeshauptstadt Thüringens",
      "Historische Altstadt mit engen Gassen — Herausforderung für Umzugs-LKW",
      "Moderate Mieten im mitteldeutschen Raum",
      "Gute ICE-Anbindung durch zentrale Lage",
    ],
    preishinweis:
      "Erfurt liegt preislich unter dem Bundesdurchschnitt und bietet besonders bei Lokalumzügen ein günstiges Niveau.",
    halteverbotKosten: "70–160 €",
    lokalKm: 10,
    fernKm: 420,
    fernZiel: "Hamburg",
  },
  {
    slug: "essen",
    name: "Essen",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "580.000",
    besonderheiten: [
      "Ruhrgebiet-typisch: moderate Preise",
      "Viele Umzüge innerhalb des Ruhrgebiets",
      "Gute Autobahnanbindung (A40, A52)",
      "Rüttenscheid und Südviertel: beliebte Altbau-Quartiere",
    ],
    preishinweis:
      "Essen bietet Ruhrgebiet-typische Preise, leicht über dem Bundesdurchschnitt aber deutlich unter den süddeutschen Großstädten.",
    halteverbotKosten: "ab ca. 60 €",
    lokalKm: 15,
    fernKm: 500,
    fernZiel: "Berlin",
  },
  {
    slug: "frankfurt",
    name: "Frankfurt am Main",
    bundesland: "HE",
    bundeslandName: "Hessen",
    einwohner: "760.000",
    besonderheiten: [
      "Viele Hochhäuser und Bürokomplexe im Bankenviertel",
      "Hoher Anteil an berufsbedingten Umzügen",
      "Gute Autobahnanbindung verkürzt Fernumzüge",
      "Nordend und Bornheim: enge Straßen, Altbau",
    ],
    preishinweis:
      "Frankfurt liegt preislich auf Bundesdurchschnitt. Berufsbedingte Umzüge können steuerlich besonders vorteilhaft sein.",
    halteverbotKosten: "ab ca. 70 €",
    lokalKm: 20,
    fernKm: 500,
    fernZiel: "Berlin",
  },
  {
    slug: "freiburg",
    name: "Freiburg",
    bundesland: "BW",
    bundeslandName: "Baden-Württemberg",
    einwohner: "ca. 230.000",
    besonderheiten: [
      "Universitätsstadt mit hoher Umzugsfrequenz",
      "Hohe Mietpreise für die Stadtgröße",
      "Ökologisch orientierte Stadt mit autofreiem Vauban-Viertel",
      "Begrenztes Parkplatzangebot in der Altstadt",
    ],
    preishinweis:
      "Freiburg liegt preislich über dem Durchschnitt vergleichbarer Städte — der angespannte Wohnungsmarkt treibt auch Umzugskosten.",
    halteverbotKosten: "100–220 €",
    lokalKm: 12,
    fernKm: 650,
    fernZiel: "Berlin",
  },
  {
    slug: "gelsenkirchen",
    name: "Gelsenkirchen",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 260.000",
    besonderheiten: [
      "Schalke 04 Heimat — Spieltage beeinflussen Verkehrsplanung",
      "Günstigstes Mietpreisniveau im Ruhrgebiet",
      "Viele Plattenbauten in Buer und Erle mit breiten Zugängen",
      "Strukturwandel bringt neue Wohnquartiere auf alten Industrieflächen",
    ],
    preishinweis:
      "Gelsenkirchen gehört zu den günstigsten NRW-Städten beim Umzug — guter Wettbewerb und niedrige Mietpreise halten die Kosten im Rahmen.",
    halteverbotKosten: "70–160 €",
    lokalKm: 10,
    fernKm: 510,
    fernZiel: "Berlin",
  },
  {
    slug: "goettingen",
    name: "Göttingen",
    bundesland: "NI",
    bundeslandName: "Niedersachsen",
    einwohner: "ca. 120.000",
    besonderheiten: [
      "Universitätsstadt — jedes Semester zahlreiche Studierenden-Umzüge",
      "Kompakte Innenstadt mit guter Erreichbarkeit",
      "Günstige Mietpreise im niedersächsischen Mittelfeld",
      "Zentrale Lage an der A7 für Fernumzüge günstig",
    ],
    preishinweis:
      "Göttingen liegt preislich unter dem Bundesdurchschnitt. Die hohe Umzugsfrequenz durch Studierende sorgt für guten Anbieterwettbewerb.",
    halteverbotKosten: "70–160 €",
    lokalKm: 10,
    fernKm: 480,
    fernZiel: "München",
  },
  {
    slug: "halle-saale",
    name: "Halle (Saale)",
    bundesland: "ST",
    bundeslandName: "Sachsen-Anhalt",
    einwohner: "ca. 240.000",
    besonderheiten: [
      "Martin-Luther-Universität mit hoher Studierenden-Umzugsfrequenz",
      "Günstigstes Preisniveau unter ostdeutschen Großstädten",
      "Viele gründerzeitliche Altbauten in der Saalestadt",
      "Nähe zu Leipzig — viele Umzüge zwischen den Städten",
    ],
    preishinweis:
      "Halle (Saale) gehört zu den günstigsten Großstädten Deutschlands. Umzugskosten liegen deutlich unter dem Bundesdurchschnitt.",
    halteverbotKosten: "60–140 €",
    lokalKm: 10,
    fernKm: 380,
    fernZiel: "Hamburg",
  },
  {
    slug: "hamburg",
    name: "Hamburg",
    bundesland: "HH",
    bundeslandName: "Hamburg",
    einwohner: "1,9 Mio.",
    besonderheiten: [
      "Teuerster Regionalfaktor in Deutschland (+8 %)",
      "Altbau in Eppendorf, Eimsbüttel — enge Treppenhäuser üblich",
      "Häufig Möbellift nötig in Gründerzeit-Vierteln",
      "Hafennähe und Brücken können Routenplanung beeinflussen",
    ],
    preishinweis:
      "Hamburg hat den höchsten Regionalfaktor im Rechner (+8 %). Besonders in den beliebten Altbau-Vierteln steigen die Kosten spürbar.",
    halteverbotKosten: "ab ca. 75 €",
    lokalKm: 20,
    fernKm: 450,
    fernZiel: "Frankfurt",
  },
  {
    slug: "hannover",
    name: "Hannover",
    bundesland: "NI",
    bundeslandName: "Niedersachsen",
    einwohner: "535.000",
    besonderheiten: [
      "Zentrale Lage — guter Ausgangspunkt für Fernumzüge",
      "Mischung aus Altbau (Linden) und Neubau (Expo-Gelände)",
      "Moderate Parkplatzsituation außerhalb der Innenstadt",
      "Messezeiten können Verfügbarkeit beeinflussen",
    ],
    preishinweis:
      "Hannover liegt auf Bundesdurchschnitt. Die zentrale Lage in Deutschland macht Fernumzüge oft günstiger als von Randlagen.",
    halteverbotKosten: "ab ca. 60 €",
    lokalKm: 15,
    fernKm: 450,
    fernZiel: "München",
  },
  {
    slug: "heidelberg",
    name: "Heidelberg",
    bundesland: "BW",
    bundeslandName: "Baden-Württemberg",
    einwohner: "ca. 160.000",
    besonderheiten: [
      "Älteste Universität Deutschlands — permanente Studierenden-Umzüge",
      "Altstadt unter Denkmalschutz mit strengen Zufahrtsbeschränkungen",
      "Hohe Mietpreise durch Tourismus- und Universitätsdruck",
      "Enge Straßen in der Altstadt erfordern oft Möbellift",
    ],
    preishinweis:
      "Heidelberg liegt preislich über dem Baden-Württemberg-Durchschnitt. Die Altstadt verursacht regelmäßig Sonderzuschläge für Parken und Liftbedarf.",
    halteverbotKosten: "100–230 €",
    lokalKm: 12,
    fernKm: 620,
    fernZiel: "Berlin",
  },
  {
    slug: "karlsruhe",
    name: "Karlsruhe",
    bundesland: "BW",
    bundeslandName: "Baden-Württemberg",
    einwohner: "ca. 310.000",
    besonderheiten: [
      "Fächerstadt mit charakteristischem Straßenlayout",
      "KIT-Universität sorgt für viele Studierenden-Umzüge",
      "Gute Bahnanbindung in alle Richtungen",
      "Mietpreise deutlich unter Stuttgart-Niveau",
    ],
    preishinweis:
      "Karlsruhe liegt preislich unter Stuttgart, profitiert aber vom gleichen baden-württembergischen Regionalfaktor.",
    halteverbotKosten: "100–200 €",
    lokalKm: 15,
    fernKm: 620,
    fernZiel: "Berlin",
  },
  {
    slug: "kassel",
    name: "Kassel",
    bundesland: "HE",
    bundeslandName: "Hessen",
    einwohner: "ca. 200.000",
    besonderheiten: [
      "Documenta-Stadt mit regelmäßigen Kultur-Großereignissen",
      "Zentrale Lage an der A7 — wichtiger Knotenpunkt für Fernumzüge",
      "Moderate Mietpreise im nordhessischen Raum",
      "Bergpark Wilhelmshöhe: steile Lagen im Westen der Stadt",
    ],
    preishinweis:
      "Kassel liegt preislich unter dem hessischen Durchschnitt. Die gute Autobahn-Lage macht es zum günstigen Ausgangspunkt für Fernumzüge.",
    halteverbotKosten: "80–180 €",
    lokalKm: 12,
    fernKm: 490,
    fernZiel: "München",
  },
  {
    slug: "kiel",
    name: "Kiel",
    bundesland: "SH",
    bundeslandName: "Schleswig-Holstein",
    einwohner: "ca. 250.000",
    besonderheiten: [
      "Landeshauptstadt Schleswig-Holsteins",
      "Hafenstadt mit Marine-Standort",
      "Moderate Mieten im norddeutschen Vergleich",
      "Wind und Wetter bei Außenumzügen beachten",
    ],
    preishinweis:
      "Kiel bietet moderate Umzugspreise, die nördliche Randlage kann bei Fernumzügen jedoch zu höheren Transportkosten führen.",
    halteverbotKosten: "80–180 €",
    lokalKm: 12,
    fernKm: 490,
    fernZiel: "München",
  },
  {
    slug: "koeln",
    name: "Köln",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "1,1 Mio.",
    besonderheiten: [
      "Viele Altbauten in Ehrenfeld und Südstadt",
      "Rheinüberquerung kann Umzugszeit verlängern",
      "Hohe Dichte an Umzugsfirmen — gute Vergleichsmöglichkeiten",
      "Karneval-Saison kann Terminverfügbarkeit einschränken",
    ],
    preishinweis:
      "Köln liegt leicht über dem Bundesdurchschnitt. Die gute Wettbewerbssituation bei Umzugsfirmen drückt die Preise aber etwas.",
    halteverbotKosten: "ab ca. 65 €",
    lokalKm: 15,
    fernKm: 550,
    fernZiel: "Berlin",
  },
  {
    slug: "krefeld",
    name: "Krefeld",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 230.000",
    besonderheiten: [
      "Historische Seidenweberstadt mit vielen gründerzeitlichen Gebäuden",
      "Günstige Mieten im Vergleich zum benachbarten Düsseldorf",
      "Viele Pendler-Umzüge ins Rhein-Ruhr-Gebiet",
      "Gute Autobahnanbindung über A44 und A57",
    ],
    preishinweis:
      "Krefeld liegt preislich unter dem NRW-Durchschnitt und bietet gute Umzugskonditionen im westlichen Ruhrgebiet.",
    halteverbotKosten: "80–180 €",
    lokalKm: 12,
    fernKm: 560,
    fernZiel: "Berlin",
  },
  {
    slug: "leipzig",
    name: "Leipzig",
    bundesland: "SN",
    bundeslandName: "Sachsen",
    einwohner: "620.000",
    besonderheiten: [
      "Günstiges Preisniveau (Faktor -5 %)",
      "Viele sanierte Altbauten mit breiten Treppenhäusern",
      "Wachsende Stadt — hohe Umzugsfrequenz",
      "Plagwitz und Südvorstadt: beliebte Umzugsziele",
    ],
    preishinweis:
      "Leipzig und Sachsen liegen rund 5 % unter dem Bundesdurchschnitt. Der Umzugsmarkt ist günstig bei guter Qualität.",
    halteverbotKosten: "ab ca. 55 €",
    lokalKm: 15,
    fernKm: 500,
    fernZiel: "München",
  },
  {
    slug: "luebeck",
    name: "Lübeck",
    bundesland: "SH",
    bundeslandName: "Schleswig-Holstein",
    einwohner: "ca. 220.000",
    besonderheiten: [
      "UNESCO-Welterbe Altstadt mit besonderen Auflagen",
      "Enge Gassen erschweren die LKW-Zufahrt erheblich",
      "Moderate Mieten im norddeutschen Raum",
      "Viele historische Gebäude mit engen Treppenhäusern",
    ],
    preishinweis:
      "Lübeck bietet moderate Preise, in der Altstadt können jedoch Zufahrtsbeschränkungen für Mehrkosten sorgen.",
    halteverbotKosten: "80–170 €",
    lokalKm: 10,
    fernKm: 500,
    fernZiel: "München",
  },
  {
    slug: "magdeburg",
    name: "Magdeburg",
    bundesland: "ST",
    bundeslandName: "Sachsen-Anhalt",
    einwohner: "ca. 240.000",
    besonderheiten: [
      "Landeshauptstadt Sachsen-Anhalts",
      "Günstige Mieten mit viel Leerstand",
      "Gute Anbindung über die A2",
      "Viele Plattenbauten mit breiten Treppenhäusern",
    ],
    preishinweis:
      "Magdeburg gehört zu den günstigsten Landeshauptstädten Deutschlands — sowohl bei Mieten als auch bei Umzugskosten.",
    halteverbotKosten: "60–150 €",
    lokalKm: 12,
    fernKm: 450,
    fernZiel: "München",
  },
  {
    slug: "mainz",
    name: "Mainz",
    bundesland: "RP",
    bundeslandName: "Rheinland-Pfalz",
    einwohner: "ca. 220.000",
    besonderheiten: [
      "Landeshauptstadt Rheinland-Pfalz und ZDF-Standort",
      "Lage im Rhein-Main-Gebiet mit angespanntem Wohnungsmarkt",
      "Altstadt mit engen Gassen und Zufahrtsbeschränkungen",
      "Viele Pendler-Umzüge aus/nach Frankfurt und Wiesbaden",
    ],
    preishinweis:
      "Mainz profitiert vom Rhein-Main-Preisniveau — Umzugskosten liegen leicht über dem Bundesdurchschnitt.",
    halteverbotKosten: "100–220 €",
    lokalKm: 15,
    fernKm: 600,
    fernZiel: "Berlin",
  },
  {
    slug: "mannheim",
    name: "Mannheim",
    bundesland: "BW",
    bundeslandName: "Baden-Württemberg",
    einwohner: "ca. 310.000",
    besonderheiten: [
      "Quadrate-Stadt mit einzigartigem Straßennetz — einfache Orientierung",
      "Zweitgrößte Stadt Baden-Württembergs nach Stuttgart",
      "Hafengebiet und Neckarfront mit besonderer Logistik",
      "Mietpreise deutlich unter Stuttgart- und Heidelberg-Niveau",
    ],
    preishinweis:
      "Mannheim liegt preislich im mittleren Baden-Württemberg-Bereich. Der Quadrate-Stadtplan erleichtert die Umzugsplanung erheblich.",
    halteverbotKosten: "100–200 €",
    lokalKm: 15,
    fernKm: 610,
    fernZiel: "Berlin",
  },
  {
    slug: "moenchengladbach",
    name: "Mönchengladbach",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 260.000",
    besonderheiten: [
      "Fünftgrößte Stadt NRWs mit weitläufiger Stadtstruktur",
      "Moderate Mietpreise zwischen Düsseldorf und den Niederlanden",
      "Viele Einfamilienhausgebiete mit guter LKW-Zugänglichkeit",
      "Gute Anbindung über A44 und A61 für Fernumzüge",
    ],
    preishinweis:
      "Mönchengladbach liegt preislich unter dem NRW-Durchschnitt. Die ausgedehnte Stadtstruktur kann Lokalumzüge etwas verlängern.",
    halteverbotKosten: "80–180 €",
    lokalKm: 15,
    fernKm: 580,
    fernZiel: "Berlin",
  },
  {
    slug: "muenchen",
    name: "München",
    bundesland: "BY",
    bundeslandName: "Bayern",
    einwohner: "1,5 Mio.",
    besonderheiten: [
      "Höchstes Preisniveau unter allen deutschen Großstädten",
      "Viele Umzüge in Neubaugebiete (Freiham, Obersendling)",
      "Strenge Parkvorschriften in der Altstadt",
      "Hohe Nachfrage — frühzeitig Firma buchen",
    ],
    preishinweis:
      "München ist der teuerste Umzugsstandort Deutschlands. Der Regionalfaktor liegt rund 6 % über dem Bundesdurchschnitt.",
    halteverbotKosten: "ab ca. 80 €",
    lokalKm: 20,
    fernKm: 600,
    fernZiel: "Berlin",
  },
  {
    slug: "muenster",
    name: "Münster",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 315.000",
    besonderheiten: [
      "Fahrradstadt Nummer 1 — Umzüge profitieren von gut organisierten Wegen",
      "Westfälische Wilhelms-Universität mit 50.000 Studierenden",
      "Historische Innenstadt nach dem Krieg wiederaufgebaut",
      "Viele Neubauprojekte im Stadtumland",
    ],
    preishinweis:
      "Münster liegt leicht über dem NRW-Durchschnitt. Die hohe Lebensqualität und Universitätsnachfrage treiben Mieten und Umzugspreise.",
    halteverbotKosten: "90–190 €",
    lokalKm: 15,
    fernKm: 540,
    fernZiel: "München",
  },
  {
    slug: "nuernberg",
    name: "Nürnberg",
    bundesland: "BY",
    bundeslandName: "Bayern",
    einwohner: "520.000",
    besonderheiten: [
      "Altstadt mit engen Gassen und Fachwerk",
      "Günstiger als München, aber bayerischer Regionalfaktor",
      "Gute Autobahnanbindung nach Süd- und Mitteldeutschland",
      "Viele Umzüge zwischen Nürnberg und München",
    ],
    preishinweis:
      "Nürnberg teilt sich den bayerischen Regionalfaktor (+6 %) mit München, liegt aber bei den Lebenshaltungskosten deutlich darunter.",
    halteverbotKosten: "ab ca. 70 €",
    lokalKm: 15,
    fernKm: 450,
    fernZiel: "Berlin",
  },
  {
    slug: "oberhausen",
    name: "Oberhausen",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 210.000",
    besonderheiten: [
      "Centro Oberhausen — Europas größtes Einkaufszentrum beeinflusst Verkehrsflüsse",
      "Günstigstes Mietpreisniveau im westlichen Ruhrgebiet",
      "Viele Plattenbauten aus den 1960er-Jahren mit breiten Zugängen",
      "Kurze Wege zu Duisburg, Essen und Mühlheim",
    ],
    preishinweis:
      "Oberhausen gehört zu den günstigsten Ruhrgebietsstädten beim Umzug — niedriges Mietpreisniveau und guter Anbieterwettbewerb.",
    halteverbotKosten: "70–160 €",
    lokalKm: 10,
    fernKm: 530,
    fernZiel: "Berlin",
  },
  {
    slug: "oldenburg",
    name: "Oldenburg",
    bundesland: "NI",
    bundeslandName: "Niedersachsen",
    einwohner: "ca. 170.000",
    besonderheiten: [
      "Universitätsstadt mit Carl von Ossietzky Universität",
      "Fahrradfreundliche Flachland-Stadt mit gut erschlossenem Stadtgebiet",
      "Moderate Mietpreise im niedersächsischen Vergleich",
      "Nähe zur niederländischen Grenze — internationale Umzüge möglich",
    ],
    preishinweis:
      "Oldenburg bietet günstige Umzugspreise im niedersächsischen Mittelfeld. Die kompakte Stadtstruktur hält Lokalumzüge kurz.",
    halteverbotKosten: "70–160 €",
    lokalKm: 12,
    fernKm: 580,
    fernZiel: "München",
  },
  {
    slug: "osnabrueck",
    name: "Osnabrück",
    bundesland: "NI",
    bundeslandName: "Niedersachsen",
    einwohner: "ca. 165.000",
    besonderheiten: [
      "Friedensstadt des Westfälischen Friedens mit historischer Altstadt",
      "Hochschule Osnabrück und Universität sorgen für Studierenden-Umzüge",
      "Günstige Mietpreise an der Grenze zu NRW",
      "Gute Lage an der A1 und A30 für Fernumzüge",
    ],
    preishinweis:
      "Osnabrück liegt preislich unter dem Bundesdurchschnitt. Die Grenzlage zu NRW sorgt für guten Wettbewerb bei Umzugsfirmen.",
    halteverbotKosten: "70–160 €",
    lokalKm: 12,
    fernKm: 510,
    fernZiel: "München",
  },
  {
    slug: "potsdam",
    name: "Potsdam",
    bundesland: "BB",
    bundeslandName: "Brandenburg",
    einwohner: "185.000",
    besonderheiten: [
      "Viele denkmalgeschützte Gebäude mit Auflagen",
      "Nähe zu Berlin — oft Pendler-Umzüge",
      "Holländisches Viertel: enge Straßen",
      "Wachsende Stadt mit vielen Neubaugebieten",
    ],
    preishinweis:
      "Potsdam liegt auf Bundesdurchschnitt. Durch die Berlin-Nähe gibt es gute Auswahl an Umzugsfirmen aus beiden Städten.",
    halteverbotKosten: "ab ca. 60 €",
    lokalKm: 15,
    fernKm: 550,
    fernZiel: "München",
  },
  {
    slug: "regensburg",
    name: "Regensburg",
    bundesland: "BY",
    bundeslandName: "Bayern",
    einwohner: "ca. 155.000",
    besonderheiten: [
      "UNESCO-Weltkulturerbe Altstadt — strenge Zufahrtsbeschränkungen",
      "Mittelalterliche Gassen erfordern oft Möbellift oder Kran",
      "Universität und OTH sorgen für viele Studierenden-Umzüge",
      "Mietpreise deutlich unter München, aber steigend",
    ],
    preishinweis:
      "Regensburg teilt den bayerischen Regionalfaktor, liegt aber bei Miet- und Umzugskosten deutlich unter München. Die Altstadtlage kann Zuschläge verursachen.",
    halteverbotKosten: "100–200 €",
    lokalKm: 12,
    fernKm: 500,
    fernZiel: "Berlin",
  },
  {
    slug: "rostock",
    name: "Rostock",
    bundesland: "MV",
    bundeslandName: "Mecklenburg-Vorpommern",
    einwohner: "210.000",
    besonderheiten: [
      "Günstiges Preisniveau (Faktor -5 %)",
      "Hafenstadt — Fernumzüge Richtung Süden dauern länger",
      "Plattenbau-Gebiete: oft ohne Aufzug, aber breite Treppenhäuser",
      "KTV (Kröpeliner-Tor-Vorstadt): beliebtes Altbau-Viertel",
    ],
    preishinweis:
      "Mecklenburg-Vorpommern gehört zu den günstigsten Regionen Deutschlands. Die nördliche Lage macht Fernumzüge aber etwas teurer.",
    halteverbotKosten: "ab ca. 50 €",
    lokalKm: 15,
    fernKm: 650,
    fernZiel: "München",
  },
  {
    slug: "saarbruecken",
    name: "Saarbrücken",
    bundesland: "SL",
    bundeslandName: "Saarland",
    einwohner: "ca. 180.000",
    besonderheiten: [
      "Landeshauptstadt des Saarlands an der französischen Grenze",
      "Viele grenzüberschreitende Umzüge nach Frankreich und Luxemburg",
      "Günstigstes Mietpreisniveau unter den westdeutschen Landeshauptstädten",
      "Universität des Saarlandes mit regelmäßigen Studierenden-Umzügen",
    ],
    preishinweis:
      "Saarbrücken bietet günstige Umzugspreise deutlich unter dem Bundesdurchschnitt. Die Grenznähe ermöglicht internationalen Vergleich.",
    halteverbotKosten: "70–160 €",
    lokalKm: 12,
    fernKm: 660,
    fernZiel: "Berlin",
  },
  {
    slug: "stuttgart",
    name: "Stuttgart",
    bundesland: "BW",
    bundeslandName: "Baden-Württemberg",
    einwohner: "635.000",
    besonderheiten: [
      "Hügellage erschwert Zufahrt in manchen Stadtteilen",
      "Stäffele (Treppen) statt Straßen in Halbhöhenlagen",
      "Kessellage bedeutet oft steile Zufahrten",
      "Hoher Anteil an Einfamilienhäusern im Umland",
    ],
    preishinweis:
      "Stuttgart und Baden-Württemberg liegen rund 6 % über dem Bundesdurchschnitt. Die Topografie kann Sonderzuschläge verursachen.",
    halteverbotKosten: "ab ca. 70 €",
    lokalKm: 20,
    fernKm: 600,
    fernZiel: "Berlin",
  },
  {
    slug: "wiesbaden",
    name: "Wiesbaden",
    bundesland: "HE",
    bundeslandName: "Hessen",
    einwohner: "ca. 280.000",
    besonderheiten: [
      "Landeshauptstadt Hessens und historische Kurstadt",
      "Gehobenes Preisniveau in den Villenvierteln",
      "Viele Altbauten mit hohen Decken und breiten Treppenhäusern",
      "Nähe zu Frankfurt und Mainz für Pendler-Umzüge",
    ],
    preishinweis:
      "Wiesbaden liegt preislich im oberen Bereich, besonders die Villenviertel und Kurgebiete treiben das Niveau nach oben.",
    halteverbotKosten: "100–220 €",
    lokalKm: 15,
    fernKm: 600,
    fernZiel: "Berlin",
  },
  {
    slug: "wolfsburg",
    name: "Wolfsburg",
    bundesland: "NI",
    bundeslandName: "Niedersachsen",
    einwohner: "ca. 125.000",
    besonderheiten: [
      "VW-Konzernzentrale — dominanter Arbeitgeber mit vielen Werksumzügen",
      "Hoher Anteil an berufsbedingten Umzügen durch Automobilindustrie",
      "Autostadt und Phaeno als architektonische Besonderheiten",
      "Moderate Mieten trotz hohen Einkommenslevels",
    ],
    preishinweis:
      "Wolfsburg liegt preislich im niedersächsischen Mittelfeld. Berufsbedingte Umzüge durch VW sind häufig steuerlich absetzbar.",
    halteverbotKosten: "80–170 €",
    lokalKm: 10,
    fernKm: 550,
    fernZiel: "München",
  },
  {
    slug: "wuppertal",
    name: "Wuppertal",
    bundesland: "NW",
    bundeslandName: "Nordrhein-Westfalen",
    einwohner: "ca. 355.000",
    besonderheiten: [
      "Bergisches Land: steile Hänge erfordern besondere Umzugsplanung",
      "Historische Schwebebahn als Wahrzeichen der stark hügeligen Stadt",
      "Günstigere Mietpreise als im benachbarten Düsseldorf",
      "Viele Altbauten in Barmen und Elberfeld mit engen Treppenhäusern",
    ],
    preishinweis:
      "Wuppertal liegt preislich unter dem NRW-Durchschnitt. Die bergige Topografie kann jedoch Sonderzuschläge für schwierige Zufahrten verursachen.",
    halteverbotKosten: "80–180 €",
    lokalKm: 15,
    fernKm: 560,
    fernZiel: "Berlin",
  },
  {
    slug: "wuerzburg",
    name: "Würzburg",
    bundesland: "BY",
    bundeslandName: "Bayern",
    einwohner: "ca. 130.000",
    besonderheiten: [
      "Mainfranken-Zentrum mit Residenz als UNESCO-Weltkulturerbe",
      "Julius-Maximilians-Universität mit hoher Studierenden-Umzugsfrequenz",
      "Historische Altstadt mit engen Gassen und strengen Parkauflagen",
      "Weinbauregion Franken — viele Weingüter im unmittelbaren Stadtgebiet",
    ],
    preishinweis:
      "Würzburg teilt den bayerischen Regionalfaktor, liegt aber bei Miet- und Umzugskosten deutlich unter München. Die Altstadt verursacht gelegentlich Liftkosten.",
    halteverbotKosten: "90–200 €",
    lokalKm: 12,
    fernKm: 480,
    fernZiel: "Berlin",
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((c) => c.slug);
}
