import type { UmzugFormData } from "./types";

export const STORAGE_KEY = "meinumzugsrechner_form_v1";

export function getDefaultForm(): UmzugFormData {
  const z = (n = 0) => n;
  return {
    buildingA: {
      bundesland: "HE",
      landkreisAgs: "00000",
      stadtOrt: "",
      etage: "eg",
      aufzug: "ja",
      treppenhaus: "normal",
      parkentfernung: "0_10",
      halteverbot: "weiss_nicht",
      gebaeudetyp: "neubau",
    },
    buildingB: {
      gleicheStadt: true,
      bundesland: "HE",
      landkreisAgs: "00000",
      stadtOrt: "",
      etage: "eg",
      aufzug: "ja",
      treppenhaus: "normal",
      parkentfernung: "0_10",
      halteverbot: "weiss_nicht",
      gebaeudetyp: "neubau",
    },
    distance: {
      km: 0,
      umzugsdatum: new Date().toISOString().slice(0, 10),
    },
    inventory: {
      schlafzimmer: {
        bett_einzel: z(),
        bett_doppel: z(),
        boxspringbett: z(),
        kleiderschrank_klein: z(),
        kleiderschrank_mittel: z(),
        kleiderschrank_gross: z(),
        kleiderschrank_begehbar: z(),
        kommode: z(),
        nachttisch: z(),
        spiegel_gross: z(),
        matratze_extra: z(),
      },
      wohnzimmer: {
        sofa_2sitzer: z(),
        sofa_3sitzer: z(),
        sofa_l_form: z(),
        sessel: z(),
        couchtisch: z(),
        tv_moebel: z(),
        regal_klein: z(),
        regal_gross: z(),
        vitrine: z(),
        teppich_gross: z(),
      },
      kueche: {
        kueche_vorhanden: "nein",
        kueche_laufmeter: "bis_2m",
        kuehlschrank: "keiner",
        herd: "keiner",
        geschirrspueler: "keiner",
        waschmaschine: z(),
        trockner: z(),
      },
      buero: {
        schreibtisch_normal: z(),
        schreibtisch_eck: z(),
        buerostuhl: z(),
        buecherregal: z(),
        drucker: z(),
      },
      keller: {
        fahrrad: z(),
        ebike: z(),
        motorrad: z(),
        werkzeugschrank: z(),
        kellerregal: z(),
      },
      gartengeraete: "wenig",
      sperrgut: {
        klavier: z(),
        fluegel: z(),
        safe_schwer: z(),
        aquarium_gross: z(),
        kunst_antik: false,
        kunst_antik_text: "",
      },
      kartons: {
        karton_standard: z(),
        karton_buch: z(),
        haengekarton: z(),
        karton_spezial: z(),
      },
    },
    extras: {
      einpackservice_komplett: false,
      einpackservice_teilweise: false,
      auspackservice: false,
      moebelmontage: false,
      kueche_demo_montage: false,
      elektro_anschluss: false,
      halteverbot_service: false,
      verpackungsmaterial: false,
      entruempelung: false,
      zwischenlagerung: false,
      reinigung_alt: false,
      moebellift: false,
      transportversicherung: false,
      zwischenlagerung_tage: 0,
      zwischenlagerung_m3: 0,
      entruempelung_m3: 0,
    },
    summary: {
      nutzungsart: "privat",
      agbAccepted: false,
    },
  };
}
